name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore src/MKCache/MKCache.csproj
      - name: Build
        run: dotnet build src/MKCache/MKCache.csproj -c Release --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5 SDK and runtime
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Tests net5.0 on .NET 5
        run: |
          dotnet build src/MKCache/MKCache.csproj -c Release --framework netstandard2.0
          dotnet build tests/MKCache.Tests/MKCache.Tests.csproj -c Release --framework net5.0
          dotnet test --no-build --verbosity normal -c Release --framework net5.0

  coverage:
    if: ${{ github.event_name == 'push' }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - run: dotnet build -c Debug src/MKCache/MKCache.csproj
      - run: dotnet build -c Debug tests/MKCache.Tests/MKCache.Tests.csproj --framework net5.0
      - name: Collect coverage
        run: dotnet test -c Debug --framework net5.0 /p:CollectCoverage=true /p:CoverletOutput=coverage/ /p:CoverletOutputFormat=lcov
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage.info
          path: tests/MKCache.Tests/coverage/coverage.info
      - name: Upload to Coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: tests/MKCache.Tests/coverage/coverage.info
